src/view/Account-Creation.html, src/view/Account-Recovery.html, src/view/Generals.css
Added account creation and account recovery htmls with basic layout + "Generals.css" file
=> Account recover / Account creation development

.dockerignore, Dockerfile
Created a dockerfile that allows us to run our service in a containerized format
=> Scrum #44 Create a linux executable that can host our service

src/routes.js
Completed the Login Route, simple add.
=> SCRUM-133 Login Route Completed

src/routes.js
Admin page is still being worked on, but I added the route in advance.
=> Scrum 135 - added admin page route

src/routes.js
Added the route for the account recovery page.
=> Added account recovery route

src/routes.js
Added the route for the account creation page
=> Account Creation page route

src/routes.js
Set up routing for user portal.
=> Scrum 134 /portal

src/routes.js
Tested with temporary file, route will work as long as HTML is named exactly Pricing.html. New pull request as the old one wanted to merge into main.
=> Scrum 131 set up the endpoint for /pricing

src/routes.js
Added and tested the /features route. Second merge request after forgetting to switch merge destination to develop.
=> Features link added

src/Spot.js, src/SpotBack.js, src/SpotFront.js, src/index.js, src/routes.js, src/view/Account-Creation.html, src/view/Account-Recovery.html, src/view/Admin-Account-View.html, src/view/Admin-Page.html, src/view/Login.html, src/view/Pricing.html, src/view/ProjectView.html, src/view/UserWebBackend.html, src/view/canvas.html, src/view/css/Assets.css, src/view/css/Generals.css, src/view/features.html, src/view/index.html, src/view/user_portal.html
Created two Spot files, with documentation on how to use each.
SpotFront is for global CSS variables.
SpotBack is for global backend variables.
Also updated all HTML files to integrate SpotFront, and tested them to ensure they looked correct. SpotBack has no variables currently within, but it has been tested and documentation on how to add and use said variables has been added.
Awaiting merge into development.
=> Scrum 160 spot file

package.json, src/CookieController.js, src/index.js, src/routes.js
Added the CookieController.js file, with methods to create and control cookies.
Added a basic functionality so that when someone travels to /loggingIn they have the loggedIn status applied. When going back to the /loggingIn directory again, they have the loggedAgain status applied. Then going to /deleteCookie removes the cookie from their account.
Added a basic logic so that, when someone has no cookie or status, upon going to the / directory they are sent to the Features page. With the loggedIn status they travel to the Portal page. With the /loggedAgain status they are sent to the ProjectView page.
This is a system that needs to be added to and reworked; at the moment the system works with only one cookie (although the CookieController file should work with multiple). The intent is that …
=> SCRUM-164, added basic cookie functionality for future application.

src/view/css/Assets.css, src/view/features.html
Added html features list to features.html and added css to assets.css relating to created objects.
=> Scrum 167 168 features page text

docs/makedocs.md
added an example of how to create a new documentation document
=> Updated documentation

blueprint/src/app/FTU-main/page.js, blueprint/src/app/Pricing/page.js, blueprint/src/app/globals.css
Refactored the Pricing page and FTU-main page to use the navbar component and work with next.js.
=> Scrum #192 #193

blueprint/src/app/Admin-Page/page.js, blueprint/src/app/Features/page.js, blueprint/src/app/login/page.js
=> Scrum-197 scrum-194 scrum-198 react changes 

blueprint/src/app/canvas/page.js
react refactor for the canvas page
=> Creates page.js for canvas

docs/.obsidian/graph.json, docs/.obsidian/workspace.json, docs/Program Structure/CSS Organization.md
Added documentation for CSS files.
Added a /styles directory, however I am not sure if that will go through to the git or not.
=> Adding documentation and a /src directory

docs/.obsidian/workspace.json, docs/Program Structure/CSS Organization.md
Ensured subsections in the CSS Formatting documentation have ## in them.
=> Format corrected, extra # added to subtitles.

blueprint/lib/connection.js, blueprint/lib/construction.js, blueprint/lib/siteQueries.js, blueprint/lib/test/connection.test.js, blueprint/lib/test/construction.test.js, blueprint/lib/test/siteQueries.test.js, blueprint/lib/test/utility.test.js, blueprint/lib/userQueries.js, blueprint/lib/utility.js, blueprint/package.json, package.json
Input: None
Output: Returns the global database connection object.
Input: None
Output: Opens a new database connection or reuses an existing one.
Input: None
Output: Closes the current database connection.
Input: None
Output: Destroys the current database connection.
utility.js
Input: None
Output: Commits the current transaction.
Input: None
Output: Rolls back the current transaction.
Input: None
Output: Placeholder function for parsing database data.
Input: None
Output: Validates and ensures a database connection exists.
Input: None
Output: Returns the connect method of the global connection.
Input: email (string)
Output: Retrieves a user by email.
Input: id (number)
Output: Retrieves a user by ID.
Input: user (string), password (string)
Output: Signs in a user.
Input: user (string), …
=> SCRUM-223 i'll be updating the documentation on what we can use

blueprint/src/app/Features/page.js, blueprint/src/app/Features/page.module.css
Refactored features page to nextjs/react
=> SCRUM-235_Features-Page-Refactored

blueprint/src/app/portal/page.js, blueprint/src/app/portal/page.module.css
Refactored user portal page to nextjs/react
=> SCRUM_241-User-Portal-Page-Completed

blueprint/src/app/FTU-main/FTU.module.css, blueprint/src/app/FTU-main/page.js, blueprint/src/app/api/CookieController.js, blueprint/src/app/deleteCookie/route.js, blueprint/src/app/route.js, blueprint/src/app/setCookie/route.js
Refactored the FTU-Main page into React. Changed up the page to be more responsive towards screen size.
Added the CookieController under a new folder /api. The controller itself is kind of optional as the new Navbar function provides similar functions, but it may make things slightly easier.
Added the route.js file under /app so that the user will be automatically redirected.
Added the /setCookie and the /deleteCookie routes for controlling the browser's cookies.
Finally fixed the %20 space issue in the CSS documentation.
Awaiting merge into development.
=> Finished cookie system

blueprint/src/app/UserWebBackend/page.js, blueprint/src/app/admin-account-view/page.js, blueprint/src/app/components/accountCollecter.js, blueprint/src/app/components/navbar.js, blueprint/src/app/portal/page.js
Fixed a multitude of minor bugs and errors. Ensured pages link properly.
=> Fixed routing and errors.

blueprint/src/app/UserWebBackend/UserWebBackend.module.css, blueprint/src/app/UserWebBackend/page.js
Fixed the User Web backend page to better reflect what is in the Figma.
=> Fixed User Web Backend refactor to reflect the Figma

blueprint/src/app/FTU-main/page.js
button that creates a new Wordpress site page
=> Scrum 217 button that creates a new Wordpress site page

blueprint/src/app/WordpressCRUD/page.js, blueprint/src/app/WordpressTest/page.js, blueprint/src/app/api/posts/[id]/delete/route.js, blueprint/src/app/api/posts/[id]/edit/route.js, blueprint/src/app/api/posts/add/route.js, blueprint/src/app/api/posts/route.js, blueprint/src/app/api/testenv/route.js
Description:
The major REST calls communicate with Wordpress
=> SCRUM-244: Basic functionality of Wordpress REST API connecting to local server

blueprint/src/app/account-recovery/page.module.css, blueprint/src/app/admin-page/page.module.css, blueprint/src/app/canvas/page.js, blueprint/src/app/canvas/page.module.css, blueprint/src/app/globals.css, blueprint/src/app/signup/page.module.css
centered the logo on account recovery and login page. Fixed issue where global.css was overriding the css centering of my canvas page. Also fixed the "2 body" portion in global.css. It doesnt break any other page. I checked every page and everything is workingp properly.
=> some styling updates and centering

README.md
Added the timeline to the README.md file.
=> Adding the Timeline to the README file.

README.md
Added the table of contents to the readme file.
=> Added the Table of Contents

blueprint/lib/connection.js, blueprint/lib/db.js, blueprint/lib/userQueries.js, blueprint/src/app/api/signup/route.js, blueprint/src/app/signup/page.js
If having issues with db rejecting db password delete old docker images / volumes.  
Connects the create account page with the database in order for it to deliver new user data.
=> Scrum 265 

blueprint/lib/construction.js, blueprint/lib/user.js, blueprint/lib/userQueries.js, blueprint/src/app/api/signup/route.js, blueprint/src/app/signup/page.js, blueprint/src/app/signup/page.module.css, dbstart/init.sql
userAccounts table has been modified to accept a security question so if you recieve errors about a table missing you will need to restart / delete your database and the init file for the db will create it correctly.  Debug messages are directly on the /signup/ page where the security question functionality is located and will show up below the  account creation form.  If you recieve the message "Account created successfully!" after attempting to create an account with the correct information the page and the database are interacting properly.  This is a culmination of SCRUM-294 and SCRUM-295, adding a security question the account creation page and then connecting it properly with the backend database.  Some functions for interacting with the database and the database itself were changed …
=> Scrum 294 295
